CREATE TABLE users (
    Id UUID PRIMARY KEY,
    Username VARCHAR(50) NOT NULL UNIQUE,
    Email VARCHAR(100) NOT NULL UNIQUE,
    FirstName VARCHAR(50) NOT NULL,
    LastName VARCHAR(50) NOT NULL,
    Administrator BOOLEAN NOT NULL DEFAULT FALSE,
    Password VARCHAR(200) NOT NULL,
    Created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE login_sessions(
    LoginSessionId UUID PRIMARY KEY,
    UserId UUID NOT NULL,
    LoginTime TIMESTAMP NOT NULL,
    LogoutTime TIMESTAMP NOT NULL,
    SessionActive BOOLEAN NOT NULL DEFAULT TRUE,
    FOREIGN KEY (UserId) REFERENCES users(Id)
        ON DELETE CASCADE
);
